### ISSUE TITLE
ci: test the workflow

### ISSUE THREAD

**Issue by AngryMaciek** [AngryMaciek/demon-runner#5]
Refactor testfiles into a separate testdir, add various test config files.
Consult Rob for reasonable parameters

**Comment by vesmanojlovic** [comment]
Hi @AngryMaciek, sorry for the late response!!
An init_config_file.dat I've been using a lot lately is 

`parameters
{
    spatial_structure
    {
        log2_deme_carrying_capacity 7
    }
    dispersal
    {
        migration_type 0
        init_migration_rate 2e-03
        migration_edge_only 1
        migration_rate_scales_with_K 1
    }
    mutation_rates
    {
        mu_driver_birth 1e-05
        mu_passenger 0.001
        mu_driver_migration 0.01
        passenger_pop_threshold -1
    }
    fitness_effects
    {
        normal_birth_rate 0.9
        baseline_death_rate 0
        s_driver_birth 0.1
        s_passenger 0
        s_driver_migration 0
        max_relative_birth_rate 10
        max_relative_migration_rate 10
    }
    non_biological_parameters
    {
        init_pop 1
        matrix_max -1
        max_pop 1000000
        max_time 86400
        max_generations 2000
        seed 10
        write_grid 0
        write_clones_file 0
        write_demes_file 0
        record_matrix 0
        write_phylo 0
        calculate_total_diversity 0
        biopsy_size_per_sample 100
    }
}`

It takes a few seconds to run as is. I mostly vary `mu_passenger`, `s_driver_migration`, and `s_driver_birth`, which can make the execution time get out of hand pretty quickly, so I'd say decent ranges for testing are:
`mu_passenger` between 0.001 and 0.01;
`s_driver_migration` between 0 and 0.05;
`s_driver_birth` between 0.1 and 0.2.
If all of these are at the largest values (particularly `s_driver_birth`), it takes a couple minutes to execute for `max_pop` set to 100000 (if it's 1000000 as above, we're talking a while longer), but otherwise shouldn't take more than a few seconds.
